version: 0.0
os: linux
files:
  - source: / #Copy every single file into s3 bucket 
    destination: /var/www/html/ #place inside html folder for apache to run 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root